// Importações principais do Next.js
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Importação de componentes do seu projeto
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";
import CartProvider from "@/providers/cart";
import Search from "@/components/ui/search";
import SearchProvider from "@/providers/use-search";
import WhatsAppButton from "@/components/ui/WhatsAppButton";

// Biblioteca para notificações (Toastify)
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Análises da Vercel
import { Analytics } from "@vercel/analytics/react";

// Fonte global (Inter)
const inter = Inter({ subsets: ["latin"] });

// Metadados globais do app (aparecem no <head>)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout raiz - é usado em TODAS as páginas
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      {/* Classe global da fonte vem aqui */}
      <body className={inter.className}>
        {/* Estrutura principal em coluna (header > conteúdo > footer) */}
        <div className="flex h-full flex-col">
          {/* Providers globais que envolvem a aplicação */}
          <SearchProvider>
            <CartProvider>
              {/* Cabeçalho fixo em todas as páginas */}
              <Header />

              {/* Barra de busca global */}
              <Search />

              {/* Conteúdo dinâmico da página */}
              <div className="flex-1">{children}</div>

              {/* Rodapé global */}
              <Footer />

              {/* Container do Toastify (notificações) */}
              <ToastContainer
                position="top-right" // posição na tela
                theme="dark" // tema dark
                autoClose={3000} // fecha sozinho em 3s
              />
            </CartProvider>
          </SearchProvider>

          {/* Botão do WhatsApp flutuante */}
          <WhatsAppButton />

          {/* Análises da Vercel */}
          <Analytics />
        </div>
      </body>
    </html>
  );
}
