import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";
import CartProvider from "@/providers/cart";

import WhatsAppButton from "@/components/ui/WhatsAppButton";

import { ToastContainer } from "react-toastify"; // importação toastify
import "react-toastify/dist/ReactToastify.css"; // estilos toastify

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <CartProvider>
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
            {/* Container para as notificações toastify */}
            <ToastContainer position="top-right" autoClose={3000} />
          </CartProvider>
          <>
            {/* outros componentes globais */}
            <WhatsAppButton />
          </>
        </div>
      </body>
    </html>
  );
}
